# Generated by Django 3.0.8 on 2020-08-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('appbypatient', models.CharField(max_length=20)),
                ('apptodoctor', models.CharField(max_length=20)),
                ('apptime', models.TimeField()),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
