# Generated by Django 3.0.8 on 2020-08-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='clinicname',
            field=models.CharField(max_length=50),
        ),
    ]
