# Generated by Django 3.0.8 on 2020-08-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patid', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile', models.IntegerField()),
                ('pswd', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('disease', models.CharField(max_length=20)),
                ('symptoms', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('previousrecord', models.IntegerField()),
                ('covidsymptoms', models.IntegerField()),
            ],
        ),
    ]
