# Generated by Django 3.0.8 on 2020-08-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myadmin',
            fields=[
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pswd', models.CharField(max_length=20)),
            ],
        ),
    ]
