# Generated by Django 3.0.8 on 2020-08-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pswd', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('speciality', models.CharField(max_length=20)),
                ('checkintime', models.TimeField(max_length=20)),
                ('checkouttime', models.TimeField(max_length=10)),
                ('clinicname', models.CharField(max_length=30)),
                ('consultfee', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('about', models.IntegerField()),
            ],
        ),
    ]
